EMG:
  conv1: 
    filter: 32
    kernel_size: [3, 20]
    stride: [1, 1]
    padding: [1, 10]
  maxpool1:
    kernel_size: [1, 20]
  conv2:
    filter: 64
    kernel_size: [3, 3]
    stride: [1, 1]
    padding: [1, 1]
  maxpool2:
    kernel_size: [1, 2]
  conv3:
    filter: 128
    kernel_size: [3, 3]
    stride: [1, 1]
    padding: 0
  dropout1: 0.5
  fc1:
    in_channel: 1024
    out_channel: 128
  dropout2: 0.5
  fc2:
    in_channel: 128
    out_channel: 20
US: 
  conv1: 
    filter: 32
    kernel_size: [3, 16]
    stride: [1, 1]
    padding: [1, 8]
  maxpool1:
    kernel_size: [1, 16]
  conv2:
    filter: 64
    kernel_size: [3, 3]
    stride: [1, 1]
    padding: [1, 1]
  maxpool2:
    kernel_size: [1, 2]
  conv3:
    filter: 128
    kernel_size: [3, 3]
    stride: [1, 1]
    padding: 0
  dropout1: 0.5
  fc1:
    in_channel: 7680
    out_channel: 128
  dropout2: 0.5
  fc2:
    in_channel: 128
    out_channel: 20